# format: script_name|Display Name|default (on/off)
qemu.sh|QEMU/KVM|on
nano-syntax.sh|Nano syntax highlighting|on
ssh.sh|SSH|on
ufw.sh|UFW firewall|on
btrfs-home.sh|btrfs home config|on
wallpapers.sh|Wallpapers|on
kde-settings.sh|KDE settings|on
scripts.sh|Python scripts|on
restore-vm.sh|Restore VM|off
