# format: script_name|Display Name|default (on/off)
qemu.sh|qemu|off
nano-syntax.sh|nano syntax highlighting|off
ssh.sh|ssh|off
btrfs-home.sh|btrfs home config|off
wallpapers.sh|wallpapers|off
scripts.sh|sync scripts|off
fish-aliases.sh|fish aliases|off
screen.sh|screen|off
catfish.sh|catfish|off
firefox-setup.sh|firefox setup|off
wallsave.sh|wallsave script|off
walldelete.sh|walldelete script|off
sudo-config.sh|sudo config|off
plasma-config.sh|plasma config|off
