# format: script_name|Display Name|default (on/off)
qemu.sh|QEMU/KVM|off
nano-syntax.sh|Nano syntax highlighting|off
ssh.sh|SSH|off
ufw.sh|UFW firewall|off
btrfs-home.sh|btrfs home config|off
wallpapers.sh|Wallpapers|off
scripts.sh|Python scripts|off
fish-aliases.sh|Fish aliases|off
screen.sh|screen|off
